using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImportadorERP
{
    public static class LayoutManager
    {
        public static Record[] GetClientLayout()
        {
            Record[] layout =
            {
                new Record(ClientLayout.TIPO_DE_LINHA_INDEX, ClientLayout.TIPO_DE_LINHA_TAM, ClientLayout.TIPO_DE_LINHA_FORMATO),
                new Record(ClientLayout.COLIGADA_INDEX, ClientLayout.COLIGADA_TAM, ClientLayout.COLIGADA_FORMATO),
                new Record(ClientLayout.CODIGO_CLIENTE_FORNECEDOR_INDEX, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_TAM, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_FORMATO),
                new Record(ClientLayout.NOME_FANTASIA_INDEX, ClientLayout.NOME_FANTASIA_TAM, ClientLayout.NOME_FANTASIA_FORMATO),
                new Record(ClientLayout.CLIENTE_FORNECEDOR_INDEX, ClientLayout.CLIENTE_FORNECEDOR_TAM, ClientLayout.CLIENTE_FORNECEDOR_FORMATO),
            };
            return layout;
        }

        public static Record[] GetCompleteClientLayout()
        {
            Record[] layout =
            {
                new Record(ClientLayout.TIPO_DE_LINHA_INDEX, ClientLayout.TIPO_DE_LINHA_TAM, ClientLayout.TIPO_DE_LINHA_FORMATO),
                new Record(ClientLayout.COLIGADA_INDEX, ClientLayout.COLIGADA_TAM, ClientLayout.COLIGADA_FORMATO),
                new Record(ClientLayout.CODIGO_CLIENTE_FORNECEDOR_INDEX, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_TAM, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_FORMATO),
                new Record(ClientLayout.NOME_FANTASIA_INDEX, ClientLayout.NOME_FANTASIA_TAM, ClientLayout.NOME_FANTASIA_FORMATO),
                new Record(ClientLayout.NOME_INDEX, ClientLayout.NOME_TAM, ClientLayout.NOME_FORMATO),
                new Record(ClientLayout.CNPJ_CPF_INDEX, ClientLayout.CNPJ_CPF_TAM, ClientLayout.CNPJ_CPF_FORMATO),
                new Record(ClientLayout.INSCRICAO_ESTADUAL_INDEX, ClientLayout.INSCRICAO_ESTADUAL_TAM, ClientLayout.INSCRICAO_ESTADUAL_FORMATO),
                new Record(ClientLayout.CLIENTE_FORNECEDOR_INDEX, ClientLayout.CLIENTE_FORNECEDOR_TAM, ClientLayout.CLIENTE_FORNECEDOR_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_1_INDEX, ClientLayout.NAO_UTILIZADO_1_TAM, ClientLayout.NAO_UTILIZADO_1_FORMATO),
                new Record(ClientLayout.NUMERO_INDEX, ClientLayout.NUMERO_TAM, ClientLayout.NUMERO_FORMATO),
                new Record(ClientLayout.COMPLEMENTO_INDEX, ClientLayout.COMPLEMENTO_TAM, ClientLayout.COMPLEMENTO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_2_INDEX, ClientLayout.NAO_UTILIZADO_2_TAM, ClientLayout.NAO_UTILIZADO_2_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_3_INDEX, ClientLayout.NAO_UTILIZADO_3_TAM, ClientLayout.NAO_UTILIZADO_3_FORMATO),
                new Record(ClientLayout.ESTADO_INDEX, ClientLayout.ESTADO_TAM, ClientLayout.ESTADO_FORMATO),
                new Record(ClientLayout.CEP_INDEX, ClientLayout.CEP_TAM, ClientLayout.CEP_FORMATO),
                new Record(ClientLayout.TELEFONE_INDEX, ClientLayout.TELEFONE_TAM, ClientLayout.TELEFONE_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_4_INDEX, ClientLayout.NAO_UTILIZADO_4_TAM, ClientLayout.NAO_UTILIZADO_4_FORMATO),
                new Record(ClientLayout.NUMERO_PAGAMENTO_INDEX, ClientLayout.NUMERO_PAGAMENTO_TAM, ClientLayout.NUMERO_PAGAMENTO_FORMATO),
                new Record(ClientLayout.COMPLEMENTO_PAGAMENTO_INDEX, ClientLayout.COMPLEMENTO_PAGAMENTO_TAM, ClientLayout.COMPLEMENTO_PAGAMENTO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_5_INDEX, ClientLayout.NAO_UTILIZADO_5_TAM, ClientLayout.NAO_UTILIZADO_5_FORMATO),
                new Record(ClientLayout.CIDADE_DE_PAGAMENTO_INDEX, ClientLayout.CIDADE_DE_PAGAMENTO_TAM, ClientLayout.CIDADE_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.ESTADO_DE_PAGAMENTO_INDEX, ClientLayout.ESTADO_DE_PAGAMENTO_TAM, ClientLayout.ESTADO_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.CEP_DE_PAGAMENTO_INDEX, ClientLayout.CEP_DE_PAGAMENTO_TAM, ClientLayout.CEP_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.TELEFONE_DE_PAGAMENTO_INDEX, ClientLayout.TELEFONE_DE_PAGAMENTO_TAM, ClientLayout.TELEFONE_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_6_INDEX, ClientLayout.NAO_UTILIZADO_6_TAM, ClientLayout.NAO_UTILIZADO_6_FORMATO),
                new Record(ClientLayout.NUMERO_DE_ENTREGA_INDEX, ClientLayout.NUMERO_DE_ENTREGA_TAM, ClientLayout.NUMERO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.COMPLEMENTO_DE_ENTREGA_INDEX, ClientLayout.COMPLEMENTO_DE_ENTREGA_TAM, ClientLayout.COMPLEMENTO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_7_INDEX, ClientLayout.NAO_UTILIZADO_7_TAM, ClientLayout.NAO_UTILIZADO_7_FORMATO),
                new Record(ClientLayout.CIDADE_DE_ENTREGA_INDEX, ClientLayout.CIDADE_DE_ENTREGA_TAM, ClientLayout.CIDADE_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.ESTADO_DE_ENTREGA_INDEX, ClientLayout.ESTADO_DE_ENTREGA_TAM, ClientLayout.ESTADO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.CEP_DE_ENTREGA_INDEX, ClientLayout.CEP_DE_ENTREGA_TAM, ClientLayout.CEP_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.TELEFONE_DE_ENTREGA_INDEX, ClientLayout.TELEFONE_DE_ENTREGA_TAM, ClientLayout.TELEFONE_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.FAX_INDEX, ClientLayout.FAX_TAM, ClientLayout.FAX_FORMATO),
                new Record(ClientLayout.CELULAR_INDEX, ClientLayout.CELULAR_TAM, ClientLayout.CELULAR_FORMATO),
                new Record(ClientLayout.EMAIL_INDEX, ClientLayout.EMAIL_TAM, ClientLayout.EMAIL_FORMATO),
                new Record(ClientLayout.CONTATO_INDEX, ClientLayout.CONTATO_TAM, ClientLayout.CONTATO_FORMATO),
                new Record(ClientLayout.TIPO_DE_CLIENTE_FORNECEDOR_INDEX, ClientLayout.TIPO_DE_CLIENTE_FORNECEDOR_TAM, ClientLayout.TIPO_DE_CLIENTE_FORNECEDOR_FORMATO),
                new Record(ClientLayout.ATIVO_INDEX, ClientLayout.ATIVO_TAM, ClientLayout.ATIVO_FORMATO),
                new Record(ClientLayout.LIMITE_DE_CREDITO_INDEX, ClientLayout.LIMITE_DE_CREDITO_TAM, ClientLayout.LIMITE_DE_CREDITO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_8_INDEX, ClientLayout.NAO_UTILIZADO_8_TAM, ClientLayout.NAO_UTILIZADO_8_FORMATO),
                new Record(ClientLayout.VALOR_DO_ULTIMO_LANCAMENTO_INDEX, ClientLayout.VALOR_DO_ULTIMO_LANCAMENTO_TAM, ClientLayout.VALOR_DO_ULTIMO_LANCAMENTO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_9_INDEX, ClientLayout.NAO_UTILIZADO_9_TAM, ClientLayout.NAO_UTILIZADO_9_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_10_INDEX, ClientLayout.NAO_UTILIZADO_10_TAM, ClientLayout.NAO_UTILIZADO_10_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_11_INDEX, ClientLayout.NAO_UTILIZADO_11_TAM, ClientLayout.NAO_UTILIZADO_11_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_12_INDEX, ClientLayout.NAO_UTILIZADO_12_TAM, ClientLayout.NAO_UTILIZADO_12_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_13_INDEX, ClientLayout.NAO_UTILIZADO_13_TAM, ClientLayout.NAO_UTILIZADO_13_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_14_INDEX, ClientLayout.NAO_UTILIZADO_14_TAM, ClientLayout.NAO_UTILIZADO_14_FORMATO),
                new Record(ClientLayout.CAMPO_LIVRE_INDEX, ClientLayout.CAMPO_LIVRE_TAM, ClientLayout.CAMPO_LIVRE_FORMATO),
                new Record(ClientLayout.CAMPO_ALFA_1_INDEX, ClientLayout.CAMPO_ALFA_1_TAM, ClientLayout.CAMPO_ALFA_1_FORMATO),
                new Record(ClientLayout.CAMPO_ALFA_2_INDEX, ClientLayout.CAMPO_ALFA_2_TAM, ClientLayout.CAMPO_ALFA_2_FORMATO),
                new Record(ClientLayout.CAMPO_ALFA_3_INDEX, ClientLayout.CAMPO_ALFA_3_TAM, ClientLayout.CAMPO_ALFA_3_FORMATO),
                new Record(ClientLayout.VALOR_OPCIONAL_1_INDEX, ClientLayout.VALOR_OPCIONAL_1_TAM, ClientLayout.VALOR_OPCIONAL_1_FORMATO),
                new Record(ClientLayout.VALOR_OPCIONAL_2_INDEX, ClientLayout.VALOR_OPCIONAL_2_TAM, ClientLayout.VALOR_OPCIONAL_2_FORMATO),
                new Record(ClientLayout.VALOR_OPCIONAL_3_INDEX, ClientLayout.VALOR_OPCIONAL_3_TAM, ClientLayout.VALOR_OPCIONAL_3_FORMATO),
                new Record(ClientLayout.DADOS_OPCIONAL_1_INDEX, ClientLayout.DADOS_OPCIONAL_1_TAM, ClientLayout.DADOS_OPCIONAL_1_FORMATO),
                new Record(ClientLayout.DADOS_OPCIONAL_2_INDEX, ClientLayout.DADOS_OPCIONAL_2_TAM, ClientLayout.DADOS_OPCIONAL_2_FORMATO),
                new Record(ClientLayout.DADOS_OPCIONAL_3_INDEX, ClientLayout.DADOS_OPCIONAL_3_TAM, ClientLayout.DADOS_OPCIONAL_3_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_15_INDEX, ClientLayout.NAO_UTILIZADO_15_TAM, ClientLayout.NAO_UTILIZADO_15_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_16_INDEX, ClientLayout.NAO_UTILIZADO_16_TAM, ClientLayout.NAO_UTILIZADO_16_FORMATO),
                new Record(ClientLayout.DATA_INICIO_ATIVIDADES_INDEX, ClientLayout.DATA_INICIO_ATIVIDADES_TAM, ClientLayout.DATA_INICIO_ATIVIDADES_FORMATO),
                new Record(ClientLayout.PATRIMONIO_INDEX, ClientLayout.PATRIMONIO_TAM, ClientLayout.PATRIMONIO_FORMATO),
                new Record(ClientLayout.NUMERO_DE_FUNCIONARIOS_INDEX, ClientLayout.NUMERO_DE_FUNCIONARIOS_TAM, ClientLayout.NUMERO_DE_FUNCIONARIOS_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_17_INDEX, ClientLayout.NAO_UTILIZADO_17_TAM, ClientLayout.NAO_UTILIZADO_17_FORMATO),
                new Record(ClientLayout.COLIGADA_TIPO_DE_CLIENTE_FORNECEDOR_INDEX, ClientLayout.COLIGADA_TIPO_DE_CLIENTE_FORNECEDOR_TAM, ClientLayout.COLIGADA_TIPO_DE_CLIENTE_FORNECEDOR_FORMATO),
                new Record(ClientLayout.FAX_DEDICADO_INDEX, ClientLayout.FAX_DEDICADO_TAM, ClientLayout.FAX_DEDICADO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_18_INDEX, ClientLayout.NAO_UTILIZADO_18_TAM, ClientLayout.NAO_UTILIZADO_18_FORMATO),
                new Record(ClientLayout.INSCRICAO_MUNICIPAL_INDEX, ClientLayout.INSCRICAO_MUNICIPAL_TAM, ClientLayout.INSCRICAO_MUNICIPAL_FORMATO),
                new Record(ClientLayout.PESSOA_FISICA_OU_JURIDICA_INDEX, ClientLayout.PESSOA_FISICA_OU_JURIDICA_TAM, ClientLayout.PESSOA_FISICA_OU_JURIDICA_FORMATO),
                new Record(ClientLayout.CONTATO_DE_PAGAMENTO_INDEX, ClientLayout.CONTATO_DE_PAGAMENTO_TAM, ClientLayout.CONTATO_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.CONTATO_DE_ENTREGA_INDEX, ClientLayout.CONTATO_DE_ENTREGA_TAM, ClientLayout.CONTATO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.PAIS_INDEX, ClientLayout.PAIS_TAM, ClientLayout.PAIS_FORMATO),
                new Record(ClientLayout.PAIS_DE_PAGAMENTO_INDEX, ClientLayout.PAIS_DE_PAGAMENTO_TAM, ClientLayout.PAIS_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.PAIS_DE_ENTREGA_INDEX, ClientLayout.PAIS_DE_ENTREGA_TAM, ClientLayout.PAIS_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.FAX_DO_ENDERECO_DE_ENTREGA_INDEX, ClientLayout.FAX_DO_ENDERECO_DE_ENTREGA_TAM, ClientLayout.FAX_DO_ENDERECO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.EMAIL_DO_ENDERECO_DE_ENTREGA_INDEX, ClientLayout.EMAIL_DO_ENDERECO_DE_ENTREGA_TAM, ClientLayout.EMAIL_DO_ENDERECO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.FAX_DO_ENDERECO_DE_PAGAMENTO_INDEX, ClientLayout.FAX_DO_ENDERECO_DE_PAGAMENTO_TAM, ClientLayout.FAX_DO_ENDERECO_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.EMAIL_DO_ENDERECO_DE_PAGAMENTO_INDEX, ClientLayout.EMAIL_DO_ENDERECO_DE_PAGAMENTO_TAM, ClientLayout.EMAIL_DO_ENDERECO_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.CARTEIRA_DE_IDENTIDADE_INDEX, ClientLayout.CARTEIRA_DE_IDENTIDADE_TAM, ClientLayout.CARTEIRA_DE_IDENTIDADE_FORMATO),
                new Record(ClientLayout.ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_INDEX, ClientLayout.ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_TAM, ClientLayout.ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_FORMATO),
                new Record(ClientLayout.ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_INDEX, ClientLayout.ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_TAM, ClientLayout.ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_FORMATO),
                new Record(ClientLayout.CODIGO_DE_MUNICIPIO_INDEX, ClientLayout.CODIGO_DE_MUNICIPIO_TAM, ClientLayout.CODIGO_DE_MUNICIPIO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_19_INDEX, ClientLayout.NAO_UTILIZADO_19_TAM, ClientLayout.NAO_UTILIZADO_19_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_20_INDEX, ClientLayout.NAO_UTILIZADO_20_TAM, ClientLayout.NAO_UTILIZADO_20_FORMATO),
                new Record(ClientLayout.CODIGO_DE_CARGA_INDEX, ClientLayout.CODIGO_DE_CARGA_TAM, ClientLayout.CODIGO_DE_CARGA_FORMATO),
                new Record(ClientLayout.VINCULO_EMPREGATICIO_INDEX, ClientLayout.VINCULO_EMPREGATICIO_TAM, ClientLayout.VINCULO_EMPREGATICIO_FORMATO),
                new Record(ClientLayout.VALOR_FRETE_FORNECEDOR_INDEX, ClientLayout.VALOR_FRETE_FORNECEDOR_TAM, ClientLayout.VALOR_FRETE_FORNECEDOR_FORMATO),
                new Record(ClientLayout.TIPO_DE_TOMADOR_INDEX, ClientLayout.TIPO_DE_TOMADOR_TAM, ClientLayout.TIPO_DE_TOMADOR_FORMATO),
                new Record(ClientLayout.CONTRIBUINTE_ISS_INDEX, ClientLayout.CONTRIBUINTE_ISS_TAM, ClientLayout.CONTRIBUINTE_ISS_FORMATO),
                new Record(ClientLayout.NUMERO_DE_DEPENDENTES_INDEX, ClientLayout.NUMERO_DE_DEPENDENTES_TAM, ClientLayout.NUMERO_DE_DEPENDENTES_FORMATO),
                new Record(ClientLayout.EMPRESA_QUE_A_PESSOA_TRABALHA_INDEX, ClientLayout.EMPRESA_QUE_A_PESSOA_TRABALHA_TAM, ClientLayout.EMPRESA_QUE_A_PESSOA_TRABALHA_FORMATO),
                new Record(ClientLayout.ESTADO_CIVIL_INDEX, ClientLayout.ESTADO_CIVIL_TAM, ClientLayout.ESTADO_CIVIL_FORMATO),
                new Record(ClientLayout.PRODUTOR_RURAL_INDEX, ClientLayout.PRODUTOR_RURAL_TAM, ClientLayout.PRODUTOR_RURAL_FORMATO),
                new Record(ClientLayout.INSCRICAO_NO_SUFRAMA_INDEX, ClientLayout.INSCRICAO_NO_SUFRAMA_TAM, ClientLayout.INSCRICAO_NO_SUFRAMA_FORMATO),
                new Record(ClientLayout.CONTRIBUINTE_ICMS_INDEX, ClientLayout.CONTRIBUINTE_ICMS_TAM, ClientLayout.CONTRIBUINTE_ICMS_FORMATO),
                new Record(ClientLayout.ORGAO_PUBLICO_INDEX, ClientLayout.ORGAO_PUBLICO_TAM, ClientLayout.ORGAO_PUBLICO_FORMATO),
                new Record(ClientLayout.TELEFONE_COMERCIAL_INDEX, ClientLayout.TELEFONE_COMERCIAL_TAM, ClientLayout.TELEFONE_COMERCIAL_FORMATO),
                new Record(ClientLayout.CAIXA_POSTAL_INDEX, ClientLayout.CAIXA_POSTAL_TAM, ClientLayout.CAIXA_POSTAL_FORMATO),
                new Record(ClientLayout.CAIXA_POSTAL_DE_PAGAMENTO_INDEX, ClientLayout.CAIXA_POSTAL_DE_PAGAMENTO_TAM, ClientLayout.CAIXA_POSTAL_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.CAIXA_POSTAL_DE_ENTREGA_INDEX, ClientLayout.CAIXA_POSTAL_DE_ENTREGA_TAM, ClientLayout.CAIXA_POSTAL_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.CATEGORIA_DO_AUTONOMO_INDEX, ClientLayout.CATEGORIA_DO_AUTONOMO_TAM, ClientLayout.CATEGORIA_DO_AUTONOMO_FORMATO),
                new Record(ClientLayout.CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO_INDEX, ClientLayout.CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO_TAM, ClientLayout.CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO_FORMATO),
                new Record(ClientLayout.NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO_INDEX, ClientLayout.NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO_TAM, ClientLayout.NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_21_INDEX, ClientLayout.NAO_UTILIZADO_21_TAM, ClientLayout.NAO_UTILIZADO_21_FORMATO),
                new Record(ClientLayout.VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF_INDEX, ClientLayout.VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF_TAM, ClientLayout.VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF_FORMATO),
                new Record(ClientLayout.CODIGO_DA_RECEITA_INDEX, ClientLayout.CODIGO_DA_RECEITA_TAM, ClientLayout.CODIGO_DA_RECEITA_FORMATO),
                new Record(ClientLayout.NAO_UTILIZADO_22_INDEX, ClientLayout.NAO_UTILIZADO_22_TAM, ClientLayout.NAO_UTILIZADO_22_FORMATO),
                new Record(ClientLayout.CEI_INDEX, ClientLayout.CEI_TAM, ClientLayout.CEI_FORMATO),
                new Record(ClientLayout.OPTANTE_PELO_SIMPLES_INDEX, ClientLayout.OPTANTE_PELO_SIMPLES_TAM, ClientLayout.OPTANTE_PELO_SIMPLES_FORMATO),
                new Record(ClientLayout.TIPO_DE_RUA_INDEX, ClientLayout.TIPO_DE_RUA_TAM, ClientLayout.TIPO_DE_RUA_FORMATO),
                new Record(ClientLayout.TIPO_DE_BAIRRO_INDEX, ClientLayout.TIPO_DE_BAIRRO_TAM, ClientLayout.TIPO_DE_BAIRRO_FORMATO),
                new Record(ClientLayout.REGIME_ISS_INDEX, ClientLayout.REGIME_ISS_TAM, ClientLayout.REGIME_ISS_FORMATO),
                new Record(ClientLayout.RETENCAO_ISS_INDEX, ClientLayout.RETENCAO_ISS_TAM, ClientLayout.RETENCAO_ISS_FORMATO),
                new Record(ClientLayout.DATA_NASCIMENTO_INDEX, ClientLayout.DATA_NASCIMENTO_TAM, ClientLayout.DATA_NASCIMENTO_FORMATO),
                new Record(ClientLayout.DESATIVAR_DADOS_BANCARIOS_CLI_FOR_INDEX, ClientLayout.DESATIVAR_DADOS_BANCARIOS_CLI_FOR_TAM, ClientLayout.DESATIVAR_DADOS_BANCARIOS_CLI_FOR_FORMATO),
                new Record(ClientLayout.INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG_INDEX, ClientLayout.INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG_TAM, ClientLayout.INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG_FORMATO),
                new Record(ClientLayout.BAIRRO_INDEX, ClientLayout.BAIRRO_TAM, ClientLayout.BAIRRO_FORMATO),
                new Record(ClientLayout.BAIRRO_DE_ENTREGA_INDEX, ClientLayout.BAIRRO_DE_ENTREGA_TAM, ClientLayout.BAIRRO_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.BAIRRO_DE_PAGAMENTO_INDEX, ClientLayout.BAIRRO_DE_PAGAMENTO_TAM, ClientLayout.BAIRRO_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.RAMO_DE_ATIVIDADE_INDEX, ClientLayout.RAMO_DE_ATIVIDADE_TAM, ClientLayout.RAMO_DE_ATIVIDADE_FORMATO),
                new Record(ClientLayout.RUA_INDEX, ClientLayout.RUA_TAM, ClientLayout.RUA_FORMATO),
                new Record(ClientLayout.RUA_DE_PAGAMENTO_INDEX, ClientLayout.RUA_DE_PAGAMENTO_TAM, ClientLayout.RUA_DE_PAGAMENTO_FORMATO),
                new Record(ClientLayout.RUA_DE_ENTREGA_INDEX, ClientLayout.RUA_DE_ENTREGA_TAM, ClientLayout.RUA_DE_ENTREGA_FORMATO),
                new Record(ClientLayout.CODIGO_PAGAMENTO_GPS_INDEX, ClientLayout.CODIGO_PAGAMENTO_GPS_TAM, ClientLayout.CODIGO_PAGAMENTO_GPS_FORMATO),
                new Record(ClientLayout.NACIONALIDADE_INDEX, ClientLayout.NACIONALIDADE_TAM, ClientLayout.NACIONALIDADE_FORMATO),
                new Record(ClientLayout.CODIGO_MUNICIPIO_PAGAMENTO_INDEX, ClientLayout.CODIGO_MUNICIPIO_PAGAMENTO_TAM, ClientLayout.CODIGO_MUNICIPIO_PAGAMENTO_FORMATO),
                new Record(ClientLayout.CODIGO_MUNICIPIO_ENTREGA_INDEX, ClientLayout.CODIGO_MUNICIPIO_ENTREGA_TAM, ClientLayout.CODIGO_MUNICIPIO_ENTREGA_FORMATO),
                new Record(ClientLayout.ID_DO_PAIS_INDEX, ClientLayout.ID_DO_PAIS_TAM, ClientLayout.ID_DO_PAIS_FORMATO),
                new Record(ClientLayout.ID_DO_PAIS_PAGAMENTO_INDEX, ClientLayout.ID_DO_PAIS_PAGAMENTO_TAM, ClientLayout.ID_DO_PAIS_PAGAMENTO_FORMATO),
                new Record(ClientLayout.ID_DO_PAIS_ENTREGA_INDEX, ClientLayout.ID_DO_PAIS_ENTREGA_TAM, ClientLayout.ID_DO_PAIS_ENTREGA_FORMATO),
                new Record(ClientLayout.TIPO_DE_RUA_PAGAMENTO_INDEX, ClientLayout.TIPO_DE_RUA_PAGAMENTO_TAM, ClientLayout.TIPO_DE_RUA_PAGAMENTO_FORMATO),
                new Record(ClientLayout.TIPO_DE_BAIRRO_PAGAMENTO_INDEX, ClientLayout.TIPO_DE_BAIRRO_PAGAMENTO_TAM, ClientLayout.TIPO_DE_BAIRRO_PAGAMENTO_FORMATO),
                new Record(ClientLayout.TIPO_DE_RUA_ENTREGA_INDEX, ClientLayout.TIPO_DE_RUA_ENTREGA_TAM, ClientLayout.TIPO_DE_RUA_ENTREGA_FORMATO),
                new Record(ClientLayout.TIPO_DE_BAIRRO_ENTREGA_INDEX, ClientLayout.TIPO_DE_BAIRRO_ENTREGA_TAM, ClientLayout.TIPO_DE_BAIRRO_ENTREGA_FORMATO),
                new Record(ClientLayout.INDICADOR_NATUREZA_RETENCAO_NA_FONTE_INDEX, ClientLayout.INDICADOR_NATUREZA_RETENCAO_NA_FONTE_TAM, ClientLayout.INDICADOR_NATUREZA_RETENCAO_NA_FONTE_FORMATO),
            };
            return layout;

        }

    }
}
