using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImportadorERP
{
    public static class LayoutManager
    {
        public static LayoutFieldData[] GetClientLayout()
        {
            LayoutFieldData[] layout =
            {
                new LayoutFieldData("TIPO_DE_LINHA",ClientLayout.TIPO_DE_LINHA_INDEX, ClientLayout.TIPO_DE_LINHA_TAM, ClientLayout.TIPO_DE_LINHA_FORMATO),
                new LayoutFieldData("COLIGADA",ClientLayout.COLIGADA_INDEX, ClientLayout.COLIGADA_TAM, ClientLayout.COLIGADA_FORMATO),
                new LayoutFieldData("CODIGO_CLIENTE_FORNECEDOR",ClientLayout.CODIGO_CLIENTE_FORNECEDOR_INDEX, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_TAM, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_FORMATO),
                new LayoutFieldData("NOME_FANTASIA",ClientLayout.NOME_FANTASIA_INDEX, ClientLayout.NOME_FANTASIA_TAM, ClientLayout.NOME_FANTASIA_FORMATO),
                new LayoutFieldData("CLIENTE_FORNECEDOR",ClientLayout.CLIENTE_FORNECEDOR_INDEX, ClientLayout.CLIENTE_FORNECEDOR_TAM, ClientLayout.CLIENTE_FORNECEDOR_FORMATO),
            };
            return layout;
        }

        public static LayoutFieldData[] GetCompleteClientLayout()
        {
            LayoutFieldData[] layout =
            {
                new LayoutFieldData("TIPO_DE_LINHA",ClientLayout.TIPO_DE_LINHA_INDEX, ClientLayout.TIPO_DE_LINHA_TAM, ClientLayout.TIPO_DE_LINHA_FORMATO),
                new LayoutFieldData("COLIGADA",ClientLayout.COLIGADA_INDEX, ClientLayout.COLIGADA_TAM, ClientLayout.COLIGADA_FORMATO),
                new LayoutFieldData("CODIGO_CLIENTE_FORNECEDOR",ClientLayout.CODIGO_CLIENTE_FORNECEDOR_INDEX, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_TAM, ClientLayout.CODIGO_CLIENTE_FORNECEDOR_FORMATO),
                new LayoutFieldData("NOME_FANTASIA",ClientLayout.NOME_FANTASIA_INDEX, ClientLayout.NOME_FANTASIA_TAM, ClientLayout.NOME_FANTASIA_FORMATO),
                new LayoutFieldData("NOME",ClientLayout.NOME_INDEX, ClientLayout.NOME_TAM, ClientLayout.NOME_FORMATO),
                new LayoutFieldData("CNPJ_CPF",ClientLayout.CNPJ_CPF_INDEX, ClientLayout.CNPJ_CPF_TAM, ClientLayout.CNPJ_CPF_FORMATO),
                new LayoutFieldData("INSCRICAO_ESTADUAL",ClientLayout.INSCRICAO_ESTADUAL_INDEX, ClientLayout.INSCRICAO_ESTADUAL_TAM, ClientLayout.INSCRICAO_ESTADUAL_FORMATO),
                new LayoutFieldData("CLIENTE_FORNECEDOR",ClientLayout.CLIENTE_FORNECEDOR_INDEX, ClientLayout.CLIENTE_FORNECEDOR_TAM, ClientLayout.CLIENTE_FORNECEDOR_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_1",ClientLayout.NAO_UTILIZADO_1_INDEX, ClientLayout.NAO_UTILIZADO_1_TAM, ClientLayout.NAO_UTILIZADO_1_FORMATO),
                new LayoutFieldData("NUMERO",ClientLayout.NUMERO_INDEX, ClientLayout.NUMERO_TAM, ClientLayout.NUMERO_FORMATO),
                new LayoutFieldData("COMPLEMENTO",ClientLayout.COMPLEMENTO_INDEX, ClientLayout.COMPLEMENTO_TAM, ClientLayout.COMPLEMENTO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_2",ClientLayout.NAO_UTILIZADO_2_INDEX, ClientLayout.NAO_UTILIZADO_2_TAM, ClientLayout.NAO_UTILIZADO_2_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_3",ClientLayout.NAO_UTILIZADO_3_INDEX, ClientLayout.NAO_UTILIZADO_3_TAM, ClientLayout.NAO_UTILIZADO_3_FORMATO),
                new LayoutFieldData("ESTADO",ClientLayout.ESTADO_INDEX, ClientLayout.ESTADO_TAM, ClientLayout.ESTADO_FORMATO),
                new LayoutFieldData("CEP",ClientLayout.CEP_INDEX, ClientLayout.CEP_TAM, ClientLayout.CEP_FORMATO),
                new LayoutFieldData("TELEFONE",ClientLayout.TELEFONE_INDEX, ClientLayout.TELEFONE_TAM, ClientLayout.TELEFONE_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_4",ClientLayout.NAO_UTILIZADO_4_INDEX, ClientLayout.NAO_UTILIZADO_4_TAM, ClientLayout.NAO_UTILIZADO_4_FORMATO),
                new LayoutFieldData("NUMERO_PAGAMENTO",ClientLayout.NUMERO_PAGAMENTO_INDEX, ClientLayout.NUMERO_PAGAMENTO_TAM, ClientLayout.NUMERO_PAGAMENTO_FORMATO),
                new LayoutFieldData("COMPLEMENTO_PAGAMENTO",ClientLayout.COMPLEMENTO_PAGAMENTO_INDEX, ClientLayout.COMPLEMENTO_PAGAMENTO_TAM, ClientLayout.COMPLEMENTO_PAGAMENTO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_5",ClientLayout.NAO_UTILIZADO_5_INDEX, ClientLayout.NAO_UTILIZADO_5_TAM, ClientLayout.NAO_UTILIZADO_5_FORMATO),
                new LayoutFieldData("CIDADE_DE_PAGAMENTO",ClientLayout.CIDADE_DE_PAGAMENTO_INDEX, ClientLayout.CIDADE_DE_PAGAMENTO_TAM, ClientLayout.CIDADE_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("ESTADO_DE_PAGAMENTO",ClientLayout.ESTADO_DE_PAGAMENTO_INDEX, ClientLayout.ESTADO_DE_PAGAMENTO_TAM, ClientLayout.ESTADO_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("CEP_DE_PAGAMENTO",ClientLayout.CEP_DE_PAGAMENTO_INDEX, ClientLayout.CEP_DE_PAGAMENTO_TAM, ClientLayout.CEP_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("TELEFONE_DE_PAGAMENTO",ClientLayout.TELEFONE_DE_PAGAMENTO_INDEX, ClientLayout.TELEFONE_DE_PAGAMENTO_TAM, ClientLayout.TELEFONE_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_6",ClientLayout.NAO_UTILIZADO_6_INDEX, ClientLayout.NAO_UTILIZADO_6_TAM, ClientLayout.NAO_UTILIZADO_6_FORMATO),
                new LayoutFieldData("NUMERO_DE_ENTREGA",ClientLayout.NUMERO_DE_ENTREGA_INDEX, ClientLayout.NUMERO_DE_ENTREGA_TAM, ClientLayout.NUMERO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("COMPLEMENTO_DE_ENTREGA",ClientLayout.COMPLEMENTO_DE_ENTREGA_INDEX, ClientLayout.COMPLEMENTO_DE_ENTREGA_TAM, ClientLayout.COMPLEMENTO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_7",ClientLayout.NAO_UTILIZADO_7_INDEX, ClientLayout.NAO_UTILIZADO_7_TAM, ClientLayout.NAO_UTILIZADO_7_FORMATO),
                new LayoutFieldData("CIDADE_DE_ENTREGA",ClientLayout.CIDADE_DE_ENTREGA_INDEX, ClientLayout.CIDADE_DE_ENTREGA_TAM, ClientLayout.CIDADE_DE_ENTREGA_FORMATO),
                new LayoutFieldData("ESTADO_DE_ENTREGA",ClientLayout.ESTADO_DE_ENTREGA_INDEX, ClientLayout.ESTADO_DE_ENTREGA_TAM, ClientLayout.ESTADO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("CEP_DE_ENTREGA",ClientLayout.CEP_DE_ENTREGA_INDEX, ClientLayout.CEP_DE_ENTREGA_TAM, ClientLayout.CEP_DE_ENTREGA_FORMATO),
                new LayoutFieldData("TELEFONE_DE_ENTREGA",ClientLayout.TELEFONE_DE_ENTREGA_INDEX, ClientLayout.TELEFONE_DE_ENTREGA_TAM, ClientLayout.TELEFONE_DE_ENTREGA_FORMATO),
                new LayoutFieldData("FAX",ClientLayout.FAX_INDEX, ClientLayout.FAX_TAM, ClientLayout.FAX_FORMATO),
                new LayoutFieldData("CELULAR",ClientLayout.CELULAR_INDEX, ClientLayout.CELULAR_TAM, ClientLayout.CELULAR_FORMATO),
                new LayoutFieldData("EMAIL",ClientLayout.EMAIL_INDEX, ClientLayout.EMAIL_TAM, ClientLayout.EMAIL_FORMATO),
                new LayoutFieldData("CONTATO",ClientLayout.CONTATO_INDEX, ClientLayout.CONTATO_TAM, ClientLayout.CONTATO_FORMATO),
                new LayoutFieldData("TIPO_DE_CLIENTE",ClientLayout.TIPO_DE_CLIENTE_FORNECEDOR_INDEX, ClientLayout.TIPO_DE_CLIENTE_FORNECEDOR_TAM, ClientLayout.TIPO_DE_CLIENTE_FORNECEDOR_FORMATO),
                new LayoutFieldData("ATIVO",ClientLayout.ATIVO_INDEX, ClientLayout.ATIVO_TAM, ClientLayout.ATIVO_FORMATO),
                new LayoutFieldData("LIMITE_DE_CREDITO",ClientLayout.LIMITE_DE_CREDITO_INDEX, ClientLayout.LIMITE_DE_CREDITO_TAM, ClientLayout.LIMITE_DE_CREDITO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_8",ClientLayout.NAO_UTILIZADO_8_INDEX, ClientLayout.NAO_UTILIZADO_8_TAM, ClientLayout.NAO_UTILIZADO_8_FORMATO),
                new LayoutFieldData("VALOR_DO_ULTIMO_LANCAMENTO",ClientLayout.VALOR_DO_ULTIMO_LANCAMENTO_INDEX, ClientLayout.VALOR_DO_ULTIMO_LANCAMENTO_TAM, ClientLayout.VALOR_DO_ULTIMO_LANCAMENTO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_9",ClientLayout.NAO_UTILIZADO_9_INDEX, ClientLayout.NAO_UTILIZADO_9_TAM, ClientLayout.NAO_UTILIZADO_9_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_10",ClientLayout.NAO_UTILIZADO_10_INDEX, ClientLayout.NAO_UTILIZADO_10_TAM, ClientLayout.NAO_UTILIZADO_10_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_11",ClientLayout.NAO_UTILIZADO_11_INDEX, ClientLayout.NAO_UTILIZADO_11_TAM, ClientLayout.NAO_UTILIZADO_11_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_12",ClientLayout.NAO_UTILIZADO_12_INDEX, ClientLayout.NAO_UTILIZADO_12_TAM, ClientLayout.NAO_UTILIZADO_12_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_13",ClientLayout.NAO_UTILIZADO_13_INDEX, ClientLayout.NAO_UTILIZADO_13_TAM, ClientLayout.NAO_UTILIZADO_13_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_14",ClientLayout.NAO_UTILIZADO_14_INDEX, ClientLayout.NAO_UTILIZADO_14_TAM, ClientLayout.NAO_UTILIZADO_14_FORMATO),
                new LayoutFieldData("CAMPO_LIVRE",ClientLayout.CAMPO_LIVRE_INDEX, ClientLayout.CAMPO_LIVRE_TAM, ClientLayout.CAMPO_LIVRE_FORMATO),
                new LayoutFieldData("CAMPO_ALFA_1",ClientLayout.CAMPO_ALFA_1_INDEX, ClientLayout.CAMPO_ALFA_1_TAM, ClientLayout.CAMPO_ALFA_1_FORMATO),
                new LayoutFieldData("CAMPO_ALFA_2",ClientLayout.CAMPO_ALFA_2_INDEX, ClientLayout.CAMPO_ALFA_2_TAM, ClientLayout.CAMPO_ALFA_2_FORMATO),
                new LayoutFieldData("CAMPO_ALFA_3",ClientLayout.CAMPO_ALFA_3_INDEX, ClientLayout.CAMPO_ALFA_3_TAM, ClientLayout.CAMPO_ALFA_3_FORMATO),
                new LayoutFieldData("VALOR_OPCIONAL_1",ClientLayout.VALOR_OPCIONAL_1_INDEX, ClientLayout.VALOR_OPCIONAL_1_TAM, ClientLayout.VALOR_OPCIONAL_1_FORMATO),
                new LayoutFieldData("VALOR_OPCIONAL_2",ClientLayout.VALOR_OPCIONAL_2_INDEX, ClientLayout.VALOR_OPCIONAL_2_TAM, ClientLayout.VALOR_OPCIONAL_2_FORMATO),
                new LayoutFieldData("VALOR_OPCIONAL_3",ClientLayout.VALOR_OPCIONAL_3_INDEX, ClientLayout.VALOR_OPCIONAL_3_TAM, ClientLayout.VALOR_OPCIONAL_3_FORMATO),
                new LayoutFieldData("DADOS_OPCIONAL_1",ClientLayout.DADOS_OPCIONAL_1_INDEX, ClientLayout.DADOS_OPCIONAL_1_TAM, ClientLayout.DADOS_OPCIONAL_1_FORMATO),
                new LayoutFieldData("DADOS_OPCIONAL_2",ClientLayout.DADOS_OPCIONAL_2_INDEX, ClientLayout.DADOS_OPCIONAL_2_TAM, ClientLayout.DADOS_OPCIONAL_2_FORMATO),
                new LayoutFieldData("DADOS_OPCIONAL_3",ClientLayout.DADOS_OPCIONAL_3_INDEX, ClientLayout.DADOS_OPCIONAL_3_TAM, ClientLayout.DADOS_OPCIONAL_3_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_15",ClientLayout.NAO_UTILIZADO_15_INDEX, ClientLayout.NAO_UTILIZADO_15_TAM, ClientLayout.NAO_UTILIZADO_15_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_16",ClientLayout.NAO_UTILIZADO_16_INDEX, ClientLayout.NAO_UTILIZADO_16_TAM, ClientLayout.NAO_UTILIZADO_16_FORMATO),
                new LayoutFieldData("DATA_INICIO_ATIVIDADES",ClientLayout.DATA_INICIO_ATIVIDADES_INDEX, ClientLayout.DATA_INICIO_ATIVIDADES_TAM, ClientLayout.DATA_INICIO_ATIVIDADES_FORMATO),
                new LayoutFieldData("PATRIMONIO",ClientLayout.PATRIMONIO_INDEX, ClientLayout.PATRIMONIO_TAM, ClientLayout.PATRIMONIO_FORMATO),
                new LayoutFieldData("NUMERO_DE_FUNCIONARIOS",ClientLayout.NUMERO_DE_FUNCIONARIOS_INDEX, ClientLayout.NUMERO_DE_FUNCIONARIOS_TAM, ClientLayout.NUMERO_DE_FUNCIONARIOS_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_17",ClientLayout.NAO_UTILIZADO_17_INDEX, ClientLayout.NAO_UTILIZADO_17_TAM, ClientLayout.NAO_UTILIZADO_17_FORMATO),
                new LayoutFieldData("COLIGADA_TIPO_DE_CLIENTE",ClientLayout.COLIGADA_TIPO_DE_CLIENTE_FORNECEDOR_INDEX, ClientLayout.COLIGADA_TIPO_DE_CLIENTE_FORNECEDOR_TAM, ClientLayout.COLIGADA_TIPO_DE_CLIENTE_FORNECEDOR_FORMATO),
                new LayoutFieldData("FAX_DEDICADO",ClientLayout.FAX_DEDICADO_INDEX, ClientLayout.FAX_DEDICADO_TAM, ClientLayout.FAX_DEDICADO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_18",ClientLayout.NAO_UTILIZADO_18_INDEX, ClientLayout.NAO_UTILIZADO_18_TAM, ClientLayout.NAO_UTILIZADO_18_FORMATO),
                new LayoutFieldData("INSCRICAO_MUNICIPAL",ClientLayout.INSCRICAO_MUNICIPAL_INDEX, ClientLayout.INSCRICAO_MUNICIPAL_TAM, ClientLayout.INSCRICAO_MUNICIPAL_FORMATO),
                new LayoutFieldData("PESSOA_FISICA_OU_JURIDICA",ClientLayout.PESSOA_FISICA_OU_JURIDICA_INDEX, ClientLayout.PESSOA_FISICA_OU_JURIDICA_TAM, ClientLayout.PESSOA_FISICA_OU_JURIDICA_FORMATO),
                new LayoutFieldData("CONTATO_DE_PAGAMENTO",ClientLayout.CONTATO_DE_PAGAMENTO_INDEX, ClientLayout.CONTATO_DE_PAGAMENTO_TAM, ClientLayout.CONTATO_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("CONTATO_DE_ENTREGA",ClientLayout.CONTATO_DE_ENTREGA_INDEX, ClientLayout.CONTATO_DE_ENTREGA_TAM, ClientLayout.CONTATO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("PAIS",ClientLayout.PAIS_INDEX, ClientLayout.PAIS_TAM, ClientLayout.PAIS_FORMATO),
                new LayoutFieldData("PAIS_DE_PAGAMENTO",ClientLayout.PAIS_DE_PAGAMENTO_INDEX, ClientLayout.PAIS_DE_PAGAMENTO_TAM, ClientLayout.PAIS_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("PAIS_DE_ENTREGA",ClientLayout.PAIS_DE_ENTREGA_INDEX, ClientLayout.PAIS_DE_ENTREGA_TAM, ClientLayout.PAIS_DE_ENTREGA_FORMATO),
                new LayoutFieldData("FAX_DO_ENDERECO_DE_ENTREGA",ClientLayout.FAX_DO_ENDERECO_DE_ENTREGA_INDEX, ClientLayout.FAX_DO_ENDERECO_DE_ENTREGA_TAM, ClientLayout.FAX_DO_ENDERECO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("EMAIL_DO_ENDERECO_DE_ENTREGA",ClientLayout.EMAIL_DO_ENDERECO_DE_ENTREGA_INDEX, ClientLayout.EMAIL_DO_ENDERECO_DE_ENTREGA_TAM, ClientLayout.EMAIL_DO_ENDERECO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("FAX_DO_ENDERECO_DE_PAGAMENTO",ClientLayout.FAX_DO_ENDERECO_DE_PAGAMENTO_INDEX, ClientLayout.FAX_DO_ENDERECO_DE_PAGAMENTO_TAM, ClientLayout.FAX_DO_ENDERECO_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("EMAIL_DO_ENDERECO_DE_PAGAMENTO",ClientLayout.EMAIL_DO_ENDERECO_DE_PAGAMENTO_INDEX, ClientLayout.EMAIL_DO_ENDERECO_DE_PAGAMENTO_TAM, ClientLayout.EMAIL_DO_ENDERECO_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("CARTEIRA_DE_IDENTIDADE",ClientLayout.CARTEIRA_DE_IDENTIDADE_INDEX, ClientLayout.CARTEIRA_DE_IDENTIDADE_TAM, ClientLayout.CARTEIRA_DE_IDENTIDADE_FORMATO),
                new LayoutFieldData("ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE",ClientLayout.ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_INDEX, ClientLayout.ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_TAM, ClientLayout.ORGAO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_FORMATO),
                new LayoutFieldData("ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE",ClientLayout.ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_INDEX, ClientLayout.ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_TAM, ClientLayout.ESTADO_EMISSOR_DE_CARTEIRA_DE_IDENTIDADE_FORMATO),
                new LayoutFieldData("CODIGO_DE_MUNICIPIO",ClientLayout.CODIGO_DE_MUNICIPIO_INDEX, ClientLayout.CODIGO_DE_MUNICIPIO_TAM, ClientLayout.CODIGO_DE_MUNICIPIO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_19",ClientLayout.NAO_UTILIZADO_19_INDEX, ClientLayout.NAO_UTILIZADO_19_TAM, ClientLayout.NAO_UTILIZADO_19_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_20",ClientLayout.NAO_UTILIZADO_20_INDEX, ClientLayout.NAO_UTILIZADO_20_TAM, ClientLayout.NAO_UTILIZADO_20_FORMATO),
                new LayoutFieldData("CODIGO_DE_CARGA",ClientLayout.CODIGO_DE_CARGA_INDEX, ClientLayout.CODIGO_DE_CARGA_TAM, ClientLayout.CODIGO_DE_CARGA_FORMATO),
                new LayoutFieldData("VINCULO_EMPREGATICIO",ClientLayout.VINCULO_EMPREGATICIO_INDEX, ClientLayout.VINCULO_EMPREGATICIO_TAM, ClientLayout.VINCULO_EMPREGATICIO_FORMATO),
                new LayoutFieldData("VALOR_FRETE_FORNECEDOR",ClientLayout.VALOR_FRETE_FORNECEDOR_INDEX, ClientLayout.VALOR_FRETE_FORNECEDOR_TAM, ClientLayout.VALOR_FRETE_FORNECEDOR_FORMATO),
                new LayoutFieldData("TIPO_DE_TOMADOR",ClientLayout.TIPO_DE_TOMADOR_INDEX, ClientLayout.TIPO_DE_TOMADOR_TAM, ClientLayout.TIPO_DE_TOMADOR_FORMATO),
                new LayoutFieldData("CONTRIBUINTE_ISS",ClientLayout.CONTRIBUINTE_ISS_INDEX, ClientLayout.CONTRIBUINTE_ISS_TAM, ClientLayout.CONTRIBUINTE_ISS_FORMATO),
                new LayoutFieldData("NUMERO_DE_DEPENDENTES",ClientLayout.NUMERO_DE_DEPENDENTES_INDEX, ClientLayout.NUMERO_DE_DEPENDENTES_TAM, ClientLayout.NUMERO_DE_DEPENDENTES_FORMATO),
                new LayoutFieldData("EMPRESA_QUE_A_PESSOA_TRABALHA",ClientLayout.EMPRESA_QUE_A_PESSOA_TRABALHA_INDEX, ClientLayout.EMPRESA_QUE_A_PESSOA_TRABALHA_TAM, ClientLayout.EMPRESA_QUE_A_PESSOA_TRABALHA_FORMATO),
                new LayoutFieldData("ESTADO_CIVIL",ClientLayout.ESTADO_CIVIL_INDEX, ClientLayout.ESTADO_CIVIL_TAM, ClientLayout.ESTADO_CIVIL_FORMATO),
                new LayoutFieldData("PRODUTOR_RURAL",ClientLayout.PRODUTOR_RURAL_INDEX, ClientLayout.PRODUTOR_RURAL_TAM, ClientLayout.PRODUTOR_RURAL_FORMATO),
                new LayoutFieldData("INSCRICAO_NO_SUFRAMA",ClientLayout.INSCRICAO_NO_SUFRAMA_INDEX, ClientLayout.INSCRICAO_NO_SUFRAMA_TAM, ClientLayout.INSCRICAO_NO_SUFRAMA_FORMATO),
                new LayoutFieldData("CONTRIBUINTE_ICMS",ClientLayout.CONTRIBUINTE_ICMS_INDEX, ClientLayout.CONTRIBUINTE_ICMS_TAM, ClientLayout.CONTRIBUINTE_ICMS_FORMATO),
                new LayoutFieldData("ORGAO_PUBLICO",ClientLayout.ORGAO_PUBLICO_INDEX, ClientLayout.ORGAO_PUBLICO_TAM, ClientLayout.ORGAO_PUBLICO_FORMATO),
                new LayoutFieldData("TELEFONE_COMERCIAL",ClientLayout.TELEFONE_COMERCIAL_INDEX, ClientLayout.TELEFONE_COMERCIAL_TAM, ClientLayout.TELEFONE_COMERCIAL_FORMATO),
                new LayoutFieldData("CAIXA_POSTAL",ClientLayout.CAIXA_POSTAL_INDEX, ClientLayout.CAIXA_POSTAL_TAM, ClientLayout.CAIXA_POSTAL_FORMATO),
                new LayoutFieldData("CAIXA_POSTAL_DE_PAGAMENTO",ClientLayout.CAIXA_POSTAL_DE_PAGAMENTO_INDEX, ClientLayout.CAIXA_POSTAL_DE_PAGAMENTO_TAM, ClientLayout.CAIXA_POSTAL_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("CAIXA_POSTAL_DE_ENTREGA",ClientLayout.CAIXA_POSTAL_DE_ENTREGA_INDEX, ClientLayout.CAIXA_POSTAL_DE_ENTREGA_TAM, ClientLayout.CAIXA_POSTAL_DE_ENTREGA_FORMATO),
                new LayoutFieldData("CATEGORIA_DO_AUTONOMO",ClientLayout.CATEGORIA_DO_AUTONOMO_INDEX, ClientLayout.CATEGORIA_DO_AUTONOMO_TAM, ClientLayout.CATEGORIA_DO_AUTONOMO_FORMATO),
                new LayoutFieldData("CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO",ClientLayout.CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO_INDEX, ClientLayout.CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO_TAM, ClientLayout.CODIGO_BRASILEIRO_DE_OCUPACAO_DO_AUTONOMO_FORMATO),
                new LayoutFieldData("NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO",ClientLayout.NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO_INDEX, ClientLayout.NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO_TAM, ClientLayout.NUMERO_CONTRIBUINTE_INDIVIDUAL_DO_AUTONOMO_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_21",ClientLayout.NAO_UTILIZADO_21_INDEX, ClientLayout.NAO_UTILIZADO_21_TAM, ClientLayout.NAO_UTILIZADO_21_FORMATO),
                new LayoutFieldData("VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF",ClientLayout.VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF_INDEX, ClientLayout.VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF_TAM, ClientLayout.VALOR_OUTRAS_DEDUCOES_CALCULO_IRRF_FORMATO),
                new LayoutFieldData("CODIGO_DA_RECEITA",ClientLayout.CODIGO_DA_RECEITA_INDEX, ClientLayout.CODIGO_DA_RECEITA_TAM, ClientLayout.CODIGO_DA_RECEITA_FORMATO),
                new LayoutFieldData("NAO_UTILIZADO_22",ClientLayout.NAO_UTILIZADO_22_INDEX, ClientLayout.NAO_UTILIZADO_22_TAM, ClientLayout.NAO_UTILIZADO_22_FORMATO),
                new LayoutFieldData("CEI",ClientLayout.CEI_INDEX, ClientLayout.CEI_TAM, ClientLayout.CEI_FORMATO),
                new LayoutFieldData("OPTANTE_PELO_SIMPLES",ClientLayout.OPTANTE_PELO_SIMPLES_INDEX, ClientLayout.OPTANTE_PELO_SIMPLES_TAM, ClientLayout.OPTANTE_PELO_SIMPLES_FORMATO),
                new LayoutFieldData("TIPO_DE_RUA",ClientLayout.TIPO_DE_RUA_INDEX, ClientLayout.TIPO_DE_RUA_TAM, ClientLayout.TIPO_DE_RUA_FORMATO),
                new LayoutFieldData("TIPO_DE_BAIRRO",ClientLayout.TIPO_DE_BAIRRO_INDEX, ClientLayout.TIPO_DE_BAIRRO_TAM, ClientLayout.TIPO_DE_BAIRRO_FORMATO),
                new LayoutFieldData("REGIME_ISS",ClientLayout.REGIME_ISS_INDEX, ClientLayout.REGIME_ISS_TAM, ClientLayout.REGIME_ISS_FORMATO),
                new LayoutFieldData("RETENCAO_ISS",ClientLayout.RETENCAO_ISS_INDEX, ClientLayout.RETENCAO_ISS_TAM, ClientLayout.RETENCAO_ISS_FORMATO),
                new LayoutFieldData("DATA_NASCIMENTO",ClientLayout.DATA_NASCIMENTO_INDEX, ClientLayout.DATA_NASCIMENTO_TAM, ClientLayout.DATA_NASCIMENTO_FORMATO),
                new LayoutFieldData("DESATIVAR_DADOS_BANCARIOS_CLI_FOR",ClientLayout.DESATIVAR_DADOS_BANCARIOS_CLI_FOR_INDEX, ClientLayout.DESATIVAR_DADOS_BANCARIOS_CLI_FOR_TAM, ClientLayout.DESATIVAR_DADOS_BANCARIOS_CLI_FOR_FORMATO),
                new LayoutFieldData("INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG",ClientLayout.INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG_INDEX, ClientLayout.INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG_TAM, ClientLayout.INSCRICAO_ESTADUAL_ST_DO_FORNEDOR_EM_MG_FORMATO),
                new LayoutFieldData("BAIRRO",ClientLayout.BAIRRO_INDEX, ClientLayout.BAIRRO_TAM, ClientLayout.BAIRRO_FORMATO),
                new LayoutFieldData("BAIRRO_DE_ENTREGA",ClientLayout.BAIRRO_DE_ENTREGA_INDEX, ClientLayout.BAIRRO_DE_ENTREGA_TAM, ClientLayout.BAIRRO_DE_ENTREGA_FORMATO),
                new LayoutFieldData("BAIRRO_DE_PAGAMENTO",ClientLayout.BAIRRO_DE_PAGAMENTO_INDEX, ClientLayout.BAIRRO_DE_PAGAMENTO_TAM, ClientLayout.BAIRRO_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("RAMO_DE_ATIVIDADE",ClientLayout.RAMO_DE_ATIVIDADE_INDEX, ClientLayout.RAMO_DE_ATIVIDADE_TAM, ClientLayout.RAMO_DE_ATIVIDADE_FORMATO),
                new LayoutFieldData("RUA",ClientLayout.RUA_INDEX, ClientLayout.RUA_TAM, ClientLayout.RUA_FORMATO),
                new LayoutFieldData("RUA_DE_PAGAMENTO",ClientLayout.RUA_DE_PAGAMENTO_INDEX, ClientLayout.RUA_DE_PAGAMENTO_TAM, ClientLayout.RUA_DE_PAGAMENTO_FORMATO),
                new LayoutFieldData("RUA_DE_ENTREGA",ClientLayout.RUA_DE_ENTREGA_INDEX, ClientLayout.RUA_DE_ENTREGA_TAM, ClientLayout.RUA_DE_ENTREGA_FORMATO),
                new LayoutFieldData("CODIGO_PAGAMENTO_GPS",ClientLayout.CODIGO_PAGAMENTO_GPS_INDEX, ClientLayout.CODIGO_PAGAMENTO_GPS_TAM, ClientLayout.CODIGO_PAGAMENTO_GPS_FORMATO),
                new LayoutFieldData("NACIONALIDADE",ClientLayout.NACIONALIDADE_INDEX, ClientLayout.NACIONALIDADE_TAM, ClientLayout.NACIONALIDADE_FORMATO),
                new LayoutFieldData("CODIGO_MUNICIPIO_PAGAMENTO",ClientLayout.CODIGO_MUNICIPIO_PAGAMENTO_INDEX, ClientLayout.CODIGO_MUNICIPIO_PAGAMENTO_TAM, ClientLayout.CODIGO_MUNICIPIO_PAGAMENTO_FORMATO),
                new LayoutFieldData("CODIGO_MUNICIPIO_ENTREGA",ClientLayout.CODIGO_MUNICIPIO_ENTREGA_INDEX, ClientLayout.CODIGO_MUNICIPIO_ENTREGA_TAM, ClientLayout.CODIGO_MUNICIPIO_ENTREGA_FORMATO),
                new LayoutFieldData("ID_DO_PAIS",ClientLayout.ID_DO_PAIS_INDEX, ClientLayout.ID_DO_PAIS_TAM, ClientLayout.ID_DO_PAIS_FORMATO),
                new LayoutFieldData("ID_DO_PAIS_PAGAMENTO",ClientLayout.ID_DO_PAIS_PAGAMENTO_INDEX, ClientLayout.ID_DO_PAIS_PAGAMENTO_TAM, ClientLayout.ID_DO_PAIS_PAGAMENTO_FORMATO),
                new LayoutFieldData("ID_DO_PAIS_ENTREGA",ClientLayout.ID_DO_PAIS_ENTREGA_INDEX, ClientLayout.ID_DO_PAIS_ENTREGA_TAM, ClientLayout.ID_DO_PAIS_ENTREGA_FORMATO),
                new LayoutFieldData("TIPO_DE_RUA_PAGAMENTO",ClientLayout.TIPO_DE_RUA_PAGAMENTO_INDEX, ClientLayout.TIPO_DE_RUA_PAGAMENTO_TAM, ClientLayout.TIPO_DE_RUA_PAGAMENTO_FORMATO),
                new LayoutFieldData("TIPO_DE_BAIRRO_PAGAMENTO",ClientLayout.TIPO_DE_BAIRRO_PAGAMENTO_INDEX, ClientLayout.TIPO_DE_BAIRRO_PAGAMENTO_TAM, ClientLayout.TIPO_DE_BAIRRO_PAGAMENTO_FORMATO),
                new LayoutFieldData("TIPO_DE_RUA_ENTREGA",ClientLayout.TIPO_DE_RUA_ENTREGA_INDEX, ClientLayout.TIPO_DE_RUA_ENTREGA_TAM, ClientLayout.TIPO_DE_RUA_ENTREGA_FORMATO),
                new LayoutFieldData("TIPO_DE_BAIRRO_ENTREGA",ClientLayout.TIPO_DE_BAIRRO_ENTREGA_INDEX, ClientLayout.TIPO_DE_BAIRRO_ENTREGA_TAM, ClientLayout.TIPO_DE_BAIRRO_ENTREGA_FORMATO),
                new LayoutFieldData("INDICADOR_NATUREZA_RETENCAO_NA_FONTE",ClientLayout.INDICADOR_NATUREZA_RETENCAO_NA_FONTE_INDEX, ClientLayout.INDICADOR_NATUREZA_RETENCAO_NA_FONTE_TAM, ClientLayout.INDICADOR_NATUREZA_RETENCAO_NA_FONTE_FORMATO),
            };
            return layout;

        }

    }
}
